apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-binging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: secret@test.com
